In [1]:
import numpy as np

**Creating NumPy arrays**

*1D array(vector)*

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


*2D array(Matrix)*

In [3]:
mat = np.array([[1,2,3,],
                [4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


*3D array(Tensor)*

In [5]:
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


**Array Attributes**

In [7]:
print(arr.shape) # (5,) -> Shape of the array
print(mat.shape) # (2,3) -> 2 rows, 3 columns
print(tensor.shape) # 1 → Represents one outermost array (i.e., one batch or sample). it is a 3D array.
print(arr.ndim) # Number of dimensions
print(mat.ndim) # 2 dimensions
print(arr.size) # Total number of elements
print(arr.dtype) # Data type of elements

(5,)
(2, 3)
(1, 4, 2)
1
2
5
int64


**Array Operations**

*Basic math operations*

In [8]:
a = np.array([10,20,30])
b = np.array([1,2,3])

print(a+b) # addition
print(a-b) # subtraction
print(a*b) # multiplication
print(a/b) # division
print(a**2) # squaring

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[100 400 900]


*statistical functions*

In [9]:
print(np.mean(a)) # Mean
print(np.median(a)) # Median
print(np.std(a)) # standard deviation
print(np.sum(a)) # sum of elements
print(np.max(a)) # maximum value
print(np.min(a)) # minimum value

20.0
20.0
8.16496580927726
60
30
10


**Creating Special Arrays**

In [11]:
zeros = np.zeros((3,3)) # 3x3 array of zeros
print(zeros)
ones = np.ones((2,4)) # 2x4 array of ones
print(ones)
identity = np.eye(3) # 3x3 identity matrix
print(identity)
range_array = np.arange(0,10,2) # array from 0 to 10 with step 2
print(range_array)
random = np.random.rand(3,3) # 3x3 Array of Random values between 0 and 1
print(random)
linspace = np.linspace(0,1,5) # 5 evenly spaced numbers from 0 to 1
print(linspace)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[[0.46928404 0.75635929 0.2191957 ]
 [0.39096777 0.80752518 0.66151077]
 [0.99170096 0.08529199 0.46856144]]
[0.   0.25 0.5  0.75 1.  ]


*more statistics*

In [12]:
sample_array = np.array([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

In [13]:
mean_all = np.mean(sample_array)
print(mean_all)
mean_columns = np.mean(sample_array, axis = 0)
print(mean_columns)
mean_rows = np.mean(sample_array, axis=1)
print(mean_rows)

5.0
[4. 5. 6.]
[2. 5. 8.]


**Reshaping and Transposing**

In [15]:
original = np.array([1,2,3,4,5,6])
print(original)
reshaped = original.reshape(2,3)
print(reshaped)
transposed = reshaped.T
print(transposed)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


**Array indexing and slicing**

In [16]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
sprint(arr[1,1]) # accessing element at 1st row and 1st column
print(arr[0,:]) # accessing first row
print(arr[:,0]) # accessing first column
print(arr[:,1]) # accessing second column
print(arr[0:2, 1:3]) # accessing (0:2) 0 to 2 rows but not including 2 and (1:3) 1 to 3 columns not including 3 so this accesses elements at 0,1 row and 1,2 column and prints the new subarray of those elements.
diagonal = [arr[i, i] for i in range(arr.shape[0])] # accessing diagonal elements((arr.shape[0]) gives the number of rows in matrix)
print(diagonal)
print(np.diagonal(arr)) # another way of accessing diagonal elements


5
[1 2 3]
[1 4 7]
[2 5 8]
[[2 3]
 [5 6]]
[np.int64(1), np.int64(5), np.int64(9)]
[1 5 9]


In [21]:
arr_2x3 = np.array([[1,2,3],
                    [4,5,6]])
print("2x3 array:\n",arr_2x3)
print("sum of rows:\n",np.sum(arr_2x3, axis = 1))
print("sum of columns:\n",np.sum(arr_2x3, axis = 0))

2x3 array:
 [[1 2 3]
 [4 5 6]]
sum of rows:
 [ 6 15]
sum of columns:
 [5 7 9]


In [22]:
#Random 3x3 array of numbers from 1 to 11
random_arr = np.random.randint(1,11, size=(3,3))
print(random_arr)
max_column = np.max(random_arr, axis = 0)
print("maximum element in each column:\n",max_column)
std_dev = np.std(random_arr)
print("standard deviation:\n",std_dev)


[[ 6  9  3]
 [10  2  2]
 [ 8  1  6]]
maximum element in each column:
 [10  9  6]
standard deviation:
 3.154459903684087


In [24]:
#random 4x4 array of integers from 0 to 100
random_4x4 = np.random.randint(0,100, size = (4,4))
print(random_4x4)
#normalized array with values between 0 and 1
normalized = (random_4x4 - random_4x4.min())/(random_4x4.max() - random_4x4.min())
print(normalized)
#printing indices of numbers with values greater than 0.5
indices = np.where(normalized > 0.5)
print(indices)
#printing numbers with values greater than 0.5
print(normalized[indices])

[[97 79 35 45]
 [18 17 60 58]
 [28 33 67 46]
 [40 70 65  6]]
[[1.         0.8021978  0.31868132 0.42857143]
 [0.13186813 0.12087912 0.59340659 0.57142857]
 [0.24175824 0.2967033  0.67032967 0.43956044]
 [0.37362637 0.7032967  0.64835165 0.        ]]
(array([0, 0, 1, 1, 2, 3, 3]), array([0, 1, 2, 3, 2, 1, 2]))
[1.         0.8021978  0.59340659 0.57142857 0.67032967 0.7032967
 0.64835165]


In [26]:
#random 3x3 array of numbers between 0 and 1
random_3x3 = np.random.random((3,3))
print(random_3x3)
#rounding elements upto 2 decimal places
round = np.round(random_3x3, 2)
print(round)
#replacing elements less than 0.5 with 0
round[round < 0.5] = 0
print(round)

[[0.8312802  0.13134362 0.04506093]
 [0.04630392 0.33272401 0.44806772]
 [0.69370653 0.17849861 0.12761509]]
[[0.83 0.13 0.05]
 [0.05 0.33 0.45]
 [0.69 0.18 0.13]]
[[0.83 0.   0.  ]
 [0.   0.   0.  ]
 [0.69 0.   0.  ]]


In [36]:
#random 5x5 array with elements from 0 to 20
random_5x5 = np.random.randint(0,20, size=(5,5))
print(random_5x5)
even = np.count_nonzero(random_5x5 % 2 == 0)
print("count of even numbers in array:",even)

[[13  7 10 19  3]
 [ 9 10 18 19  4]
 [15 18  5  7 14]
 [ 9 17 15  1 11]
 [ 1 19  0 13  9]]
count of even numbers in array: 7
