**Array Indexing and Slicing**

In [1]:
import numpy as np

In [4]:
# Creating a sample array
arr = np.array([10,20,30,40,50,60])

# Indexing (Extracting elements)
print(arr[0]) # First element
print(arr[-1]) # Last element
print(arr[2]) # Third element

# Slicing (Extracting subarrays)
print(arr[1:4]) # Elements from index 1 to 3
print(arr[:3]) # First three elements with index from 0 to 2
print(arr[2:]) # Elements from index 2 to end
print(arr[::2]) # Every second element

# Modifying elements
arr[1] = 99
print(arr) # Updated array

10
60
30
[20 30 40]
[10 20 30]
[30 40 50 60]
[10 30 50]
[10 99 30 40 50 60]


**Boolean Indexing and Fancy Indexing**

In [6]:
arr = np.array([10, 20, 30, 40, 50, 60])

# Boolean indexing (Filter elements based on condition)
print(arr[arr > 30]) #Elements greater than 30
print(arr[arr % 20 == 0]) # Elements that are multiples of 20

# Fancy Indexing (Extract elements using a list of indices)
indices = [0,2,4]
print(arr[indices]) # Select elements at index 0,2,4

# Modifying elements using fancy indexing
arr[indices] = [100,300,500] # elements at indices 0,2,4 are changed into 100,300,500
print(arr) # Updated array

[40 50 60]
[20 40 60]
[10 30 50]
[100  20 300  40 500  60]


**Reshaping and Resizing Arrays**

In [14]:
# Creating a 1D array
arr = np.arange(1,13) # Array from 1 to 12
print("Original Array:\n", arr)

# Reshaping (changing shape without modifying data)
reshaped = arr.reshape(3,4) # Convert 1D array to 3x4 matrix
print("\nReshaped (3x4) Array:\n", reshaped)

# Flattening (converting back to 1D)
flattened = reshaped.flatten()
print("\nFlattened Array:\n", flattened)

# Resizing (modifies the original array)
arr.resize(2,6) # changes shape permanently
print("\nResized (2,6) Array:\n", arr)

# Transposing (swapping rows and columns)
transposed = reshaped.T # or np.transpose(reshaped)
print("Transposed Array:\n", transposed)


Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped (3x4) Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Resized (2,6) Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Transposed Array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


**Stacking and Splitting Arrays**

*Stacking(combining arrays)*

In [19]:
# Creating two arrays
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# Vertical Stacking (Row-wise stacking)
v_stack = np.vstack((a,b))
print("\nVertically Stacked:\n",v_stack)

# Horizontal Stacking (Column-wise stacking)
h_stack = np.hstack((a,b))
print("\nHorizontally stacked:\n",h_stack)

# Depth Stacking (Stacking along a new axis)
d_stack = np.dstack((a,b))
print("\nDepth stacked:\n",d_stack)


Vertically Stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontally stacked:
 [[1 2 5 6]
 [3 4 7 8]]

Depth stacked:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


*Splitting(Dividing Arrays)*

In [25]:
# Splitting an array into multiple smaller arrays
arr = np.arange(1,10).reshape(3,3) # 3x3 matrix with 1 to 9 numbers as element
print("\nOriginal Array:\n",arr)

# Vertical Split
v_split = np.split(arr,3) # split into 3 row wise sub-arrays
print("\nVertically split:\n",v_split)

# Horizontal split
h_split = np.hsplit(arr,3)
print("\nHorizontally split:\n",h_split)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Vertically split:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

Horizontally split:
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


**Broadcasting and Vectorization**

*Broadcasting*Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes.

In [31]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

# Broadcasting with a scaler(adding 10 to each element)
result1 = arr + 10
print("\n Adding 10 to each element:\n", result1)

# Broadcasting with a 1D array
row_vector = np.array([1, 2, 3])
result2 = arr + row_vector
print("\nAdding row vector to each row:\n", result2)

# Broadcasting with a column vector
col_vector = np.array(([1],[2],[3]))
result3 = arr + col_vector
print("\nadding column vector to each row:\n",result3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Adding 10 to each element:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Adding row vector to each row:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

adding column vector to each row:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


*Vectorization*

Vectorization speeds up operations by applying them to entire arrays instead of using loops.

In [35]:
#Using loops (slow)
arr = np.arange(1,6)
squared_loops = [x**2 for x in arr]
print("Squared using loops: ", squared_loops)

# using vectorized operations (fast)
squared_vectorized = arr**2
print("Squared using vectorization: ", squared_vectorized)

# Another Example : multiplication without loops
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

# without vectorization (loop based)
product_loop = [a[i] * b[i] for i in range(len(a))]
print("Multiplication using loops: ", product_loop)

# with vectorization
product_vectorized = a * b
print("Product using vectorization: ", product_vectorized)

Squared using loops:  [np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]
Squared using vectorization:  [ 1  4  9 16 25]
Multiplication using loops:  [np.int64(10), np.int64(40), np.int64(90), np.int64(160), np.int64(250)]
Product using vectorization:  [ 10  40  90 160 250]


**Fancy Indexing and Boolean Masking**

*Fancy Indexing*

Fancy indexing allows selecting multiple elements using index arrays.

In [38]:
arr = np.array([1,2,3,4,5,6,7,8,9])
indices = [1,3,5,7] # selecting elements at these positions

selected = arr[indices]
print("Selected elements using fancy indexing: ", selected)

# Fancy indexing in a 2D array
mat = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
row_indices = [0,2] # selecting first and last rows
col_indices = [1,2] # selecting last two columns

row = mat[row_indices,:]
print("\nselected rows using fancy indexing:\n ", row)

column = mat[:, col_indices]
print("\nselected columns using fancy indexing:\n ", column)

Selected elements using fancy indexing:  [2 4 6 8]

selected rows using fancy indexing:
  [[10 20 30]
 [70 80 90]]

selected columns using fancy indexing:
  [[20 30]
 [50 60]
 [80 90]]


*Boolean masking*

Boolean masking is used to filter elements based on conditions

In [42]:
arr = np.array([10, 25, 30, 45, 50, 65, 70])

# Applying a condition (filter elements greater than 30)
mask = arr > 30
filtered = arr[mask]

print("Boolean mask: ", mask)
print("\n filtered elements (greater than 30): ", filtered)

# Boolean masking on a 2D array
mat = np.array([[5,15,25],
                [35,45,55],
                [65,75,85]])

mask = mat > 30
filtered = mat[mask]

print("\nBoolean mask: ", mask)
print("\n filtered elements from 2d array(greater than 30):\n ", filtered)

Boolean mask:  [False False False  True  True  True  True]

 filtered elements (greater than 30):  [45 50 65 70]

Boolean mask:  [[False False False]
 [ True  True  True]
 [ True  True  True]]

 filtered elements from 2d array(greater than 30):
  [35 45 55 65 75 85]


**Copying vs. views**

*Views (shallow Copy)*

A view is a shallow copy of the original array, meaning changes in the view affect the original array.

In [44]:
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr[:3] # creating a view

print("Original array:\n ", arr)
print("\n View Array:\n ", view_arr)

# Modifying the view
view_arr[0] = 100
print("\nAfter modifying the view array:")
print("original array:",arr) # Original array changes
print("view array:",view_arr)

Original array:
  [1 2 3 4 5]

 View Array:
  [1 2 3]

After modifying the view array:
original array: [100   2   3   4   5]
view array: [100   2   3]


*Copy (Deep Copy)*

A copy creates a completely independent array, so changes do not affect the original array.

In [45]:
copy_arr = arr.copy()

print("\nOriginal array before modification: ", arr)
print("copied array before modification: ", copy_arr)

# Modifying the copy
copy_arr[0] = 999
print("\nAfter modifying array: ")
print("original array: ",arr) # original array remains unchanged
print("copied array: ", copy_arr)


Original array before modification:  [100   2   3   4   5]
copied array before modification:  [100   2   3   4   5]

After modifying array: 
original array:  [100   2   3   4   5]
copied array:  [999   2   3   4   5]
